import tkinter as tk
from cell import Cell
from tkinter import messagebox
from detail_window import Detail_window

class MainWindow:
    def on_button_click(self, cell):
        root = tk.Toplevel()
        detail_window = Detail_window(root, cell.title, cell.image_tk, cell.description)

    def __init__(self, root):
        root.title("Imágenes")

        self.cells = [ #tal y como defini en cell, el primer parametro es el nombre de la imagen, el segundo la ruta 
            Cell("Libro 1", "C:\\msys64\\home\\Alumno\\DI\\sprint1Tkinter\\catalog\\data\\unedited\\cazadores.jpg", "Es el primer libro de la exitosa serie escrita por Cassandra Clare. La historia nos transporta a un mundo secreto poblado por cazadores de sombras, seres mitad ángeles mitad humanos, que protegen a la humanidad de demonios y criaturas sobrenaturales. Clary Fray, una joven aparentemente común, se ve arrastrada a este mundo cuando presencia un asesinato demoníaco y descubre su capacidad de ver lo que otros no pueden. A medida que se adentra en esta sociedad oculta, Clary conoce a Jace, un cazador de sombras atractivo pero misterioso, y se ve envuelta en una trama llena de acción, magia y secretos familiares. \n Es una novela que combina romance, aventura y elementos sobrenaturales de manera cautivadora. La autora crea un universo rico y detallado, poblado por personajes memorables y complejos. La narrativa ágil y llena de giros mantiene a los lectores atrapados desde la primera página. Es una historia emocionante que explora temas como la lealtad, el sacrificio y la identidad, lo que la convierte en una lectura obligada para los amantes del género de fantasía urbana."),
            Cell("Libro 2", "C:\\msys64\\home\\Alumno\\DI\\sprint1Tkinter\\catalog\\data\\unedited\\ecdl.jpg", "Es una novela escrita por James Dashner, es un emocionante viaje hacia lo desconocido. La historia sigue a Thomas, quien despierta en un lugar llamado 'El Claro' sin recordar su pasado. Rodeado de un grupo de jóvenes, se ven atrapados en un laberinto mortal rodeado por muros impenetrables. Cada día, los corredores se aventuran en el laberinto en busca de una salida, luchando contra criaturas biomecánicas letales conocidas como 'Los Penitentes.' \n La narrativa de Dashner es tensa y repleta de misterio, lo que mantiene a los lectores en vilo. La construcción del mundo y los personajes es fascinante, y la dinámica del grupo refleja la lucha por la supervivencia en un entorno hostil. A medida que Thomas y sus compañeros exploran el laberinto, descubren secretos inquietantes que amenazan su existencia y su comprensión de la realidad. La historia es una montaña rusa de emoción, suspenso y acción, que te dejará ansioso por descubrir los secretos que yacen en el corazón del laberinto."),
            Cell("Libro 3", "C:\\msys64\\home\\Alumno\\DI\\sprint1Tkinter\\catalog\\data\\unedited\\harry potter.jpg", "La primera entrega de la icónica serie escrita por J.K. Rowling, nos presenta al joven huérfano Harry Potter, quien descubre su verdadera herencia como mago el día de su undécimo cumpleaños. En el mundo mágico, Harry es célebre por haber sobrevivido a un intento de asesinato por parte del tenebroso mago Lord Voldemort cuando era un bebé. Ahora, se dirige a la escuela de magia y hechicería de Hogwarts, donde comienza su viaje de autodescubrimiento. \n La novela es una entrada mágica a un universo repleto de maravillas y peligros. Rowling crea un mundo mágico detallado y cautivador, poblado por personajes memorables como Hermione y Ron, y seres mágicos como las criaturas que habitan el bosque prohibido. La trama está llena de misterio, aventura y un toque de humor. A través de las páginas de 'La Piedra Filosofal,' los lectores se sumergen en una historia que celebra la importancia del amor, la amistad y la valentía. Esta obra maestra literaria no solo ha inspirado a generaciones, sino que también ha definido el género de la literatura fantástica moderna. Es un viaje inolvidable que atrae a lectores de todas las edades."),
            Cell("Libro 4", "C:\\msys64\\home\\Alumno\\DI\\sprint1Tkinter\\catalog\\data\\unedited\\ljdh.jpg", "La novela escrita por Suzanne Collins, presenta a los lectores a un mundo distópico sombrío en el que la opresión, la desigualdad y la violencia son la norma. La historia se desarrolla en el distrito 12, un lugar empobrecido, y sigue a Katniss Everdeen, una valiente joven que se ofrece como tributo en lugar de su hermana menor en los brutales Juegos del Hambre, un evento anual en el que 24 jóvenes son obligados a luchar a muerte en un macabro espectáculo televisivo. \n La trama es emocionante y repleta de giros sorprendentes, lo que mantiene a los lectores en vilo. Katniss es una heroína compleja que se convierte en símbolo de resistencia contra el Capitolio, lo que agrega una capa de significado político a la historia. Collins explora temas como el poder, la manipulación de los medios de comunicación y la moralidad en un contexto inquietante."),
            Cell("Libro 5", "C:\\msys64\\home\\Alumno\\DI\\sprint1Tkinter\\catalog\\data\\unedited\\percy jackson.jpg", "Escrito por Rick Riordan, nos introduce en un emocionante mundo de mitología griega contemporánea. La historia sigue a Percy Jackson, un joven disléxico y con TDAH, quien descubre que es un semidiós, hijo de Poseidón. Cuando el rayo de Zeus es robado y Percy es el principal sospechoso, se embarca en una épica búsqueda para limpiar su nombre y evitar una guerra entre los dioses. \n La narrativa es rápida y llena de aventuras, con un toque de humor que hace que la historia sea accesible y entretenida para lectores de todas las edades. Los personajes son entrañables y bien desarrollados, con Percy liderando la historia con su ingenio y coraje. La mitología griega cobra vida de manera vibrante a medida que los dioses y criaturas míticas se mezclan en el mundo moderno.")
        ]

        for i, cell in enumerate(self.cells): #para cada elemento i de la lista self.cells 
            label = tk.Label(root, image= cell.image_tk, text=cell.title, compound=tk.BOTTOM)
            label.grid(row=i, column=0) #asigno un lugar en la matriz (fila i, columna 0)
            label.bind("<Button-1>", lambda event, celda = cell: self.on_button_click(celda))
